CREATE TABLE "stg_anime" (
    "MAL_ID" int,
    "Name" NVARCHAR(1000),
    "Score" NVARCHAR(200),
    "Genres" NVARCHAR(1000),
    "English name" NVARCHAR(1000),
    "Japanese name" NVARCHAR(1000),
    "Type" NVARCHAR(200),
    "Episodes" NVARCHAR(200),
    "Aired" NVARCHAR(200),
    "Premiered" NVARCHAR(100),
    "Producers" NVARCHAR(1000),
    "Licensors" NVARCHAR(1000),
    "Studios" NVARCHAR(1000),
    "Source" NVARCHAR(200),
    "Duration" NVARCHAR(200),
    "Rating" NVARCHAR(200),
    "Ranked" NVARCHAR(200),
    "Popularity" int,
    "Members" int,
    "Favorites" int,
    "Watching" int,
    "Completed" int,
    "On-Hold" int,
    "Dropped" int,
    "Plan to Watch" int,
    "Score-10" NVARCHAR(50),
    "Score-9" NVARCHAR(50),
    "Score-8" NVARCHAR(50),
    "Score-7" NVARCHAR(50),
    "Score-6" NVARCHAR(50),
    "Score-5" NVARCHAR(50),
    "Score-4" NVARCHAR(50),
    "Score-3" NVARCHAR(50),
    "Score-2" NVARCHAR(50),
    "Score-1" NVARCHAR(50)
);